# use python 3.7 as base image
FROM python:3.7

# install dependencies
RUN pip install tensorflow==2.2.0
RUN pip install -r requirements.txt

COPY trail /trail

COPY my_model

#Run  when container is launced
CMD ./kerascheck.py
